services:

  postgres:
    image: postgres:17
    container_name: legacy_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: legacy_db
      POSTGRES_USER: legacy_user
      POSTGRES_PASSWORD: legacy_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: legacy-flyway

    depends_on:
      - postgres

    command:
      - -url=jdbc:postgresql://postgres:5432/legacy_db
      - -user=legacy_user
      - -password=legacy_password
      - migrate

    volumes:
      - ./legacy-system/src/main/resources/db/migration:/flyway/sql

volumes:
  postgres_data: